all:
	gcc demo_tcpip_server.c -lpthread -o tcpserver.elf
	gcc demo_tcpip_client.c -o tcpclient.elf
#	gcc demo_select.c -o select.elf
#	g++ demo_mapred.cpp -o mapred.elf
#	gcc demo_coop.c demo_coop_person.c -o coop.elf
#	gcc demo_thread_pool.c -lpthread -o threadpool.elf
#	gcc demo_thread.c -lpthread -o thread.elf